import type { Exam } from "@/lib/mock-data-types";

export const exams: Exam[] = [
  {
    id: "e1",
    title: "Mathematikiin dund shalgalt",
    questions: [
      { id: "q1", type: "multiple-choice", question: "2 + 3 × 4 = ?", options: ["20", "14", "24", "10"], correctAnswer: "14", points: 10 },
      { id: "q2", type: "true-false", question: "√16 = 5.", correctAnswer: "False", points: 5 },
      { id: "q3", type: "short-answer", question: "x + 5 = 12 bol x = ?", correctAnswer: "7", points: 10 },
      {
        id: "q4",
        type: "matching",
        question: "Match each term to the correct description.",
        options: ["HTML", "CSS", "SQL", "Git"],
        correctAnswer: "A-2, B-3, C-1, D-4",
        points: 10,
      },
      {
        id: "q5",
        type: "fill",
        question: "2 + 5 = ___",
        correctAnswer: "7",
        points: 10,
      },
    ],
    duration: 45,
    reportReleaseMode: "after-all-classes-complete",
    scheduledClasses: [
      { classId: "10A", date: "2026-03-20", time: "09:00" },
      { classId: "10B", date: "2026-03-20", time: "14:00" },
    ],
    createdAt: "2026-03-15",
    status: "completed",
  },
  {
    id: "e2",
    title: "Niigmiin uhaany soril",
    questions: [
      {
        id: "q6",
        type: "multiple-choice",
        question: "Ardchilal gej yu ve?",
        options: [
          "Neg huni zasaglal",
          "Ard tumnii oroltsootoi zasaglal",
          "Tsergiin zasaglal",
          "Haant zasaglal",
        ],
        correctAnswer: "Ard tumnii oroltsootoi zasaglal",
        points: 10,
      },
      { id: "q7", type: "true-false", question: "Mongol uls haant zasaglaltai.", correctAnswer: "False", points: 5 },
      { id: "q8", type: "short-answer", question: "Mongol Ulsyn niislel аль hot ve?", correctAnswer: "Ulaanbaatar", points: 10 },
    ],
    duration: 30,
    reportReleaseMode: "after-all-classes-complete",
    scheduledClasses: [{ classId: "10A", date: "2026-03-25", time: "10:00" }],
    createdAt: "2026-03-18",
    status: "scheduled",
  },
  {
    id: "e3",
    title: "Fizikiin shalgalt",
    questions: [
      {
        id: "q9",
        type: "multiple-choice",
        question: "Hurd = ?",
        options: ["Zam / hugatsaa", "Hugatsaa / zam", "Mass × hurdatgal", "Huch / талбай"],
        correctAnswer: "Zam / hugatsaa",
        points: 10,
      },
      { id: "q10", type: "true-false", question: "Huchnii negj ni Newton.", correctAnswer: "True", points: 5 },
    ],
    duration: 60,
    reportReleaseMode: "after-all-classes-complete",
    scheduledClasses: [
      { classId: "10A", date: "2026-03-24", time: "11:00" },
      { classId: "10B", date: "2026-03-24", time: "13:00" },
      { classId: "10C", date: "2026-03-24", time: "15:00" },
    ],
    createdAt: "2026-03-20",
    status: "scheduled",
  },
  {
    id: "e4",
    title: "Codex test",
    questions: [
      {
        id: "q11",
        type: "multiple-choice",
        question: "Which tool did we use to update this project?",
        options: ["Codex", "Spreadsheet", "Slide deck", "Email"],
        correctAnswer: "Codex",
        points: 10,
      },
      {
        id: "q12",
        type: "short-answer",
        question: "Write the class name this test is scheduled for.",
        correctAnswer: "10B",
        points: 10,
      },
      {
        id: "q13",
        type: "true-false",
        question: "This test is available for class 10B students.",
        correctAnswer: "True",
        points: 5,
      },
    ],
    duration: 25,
    availableIndefinitely: true,
    reportReleaseMode: "after-all-classes-complete",
    scheduledClasses: [{ classId: "10B", date: "2026-04-03", time: "00:00" }],
    createdAt: "2026-04-03",
    status: "scheduled",
  },
];
